#:schema node_modules/wrangler/config-schema.json
name = "sveltekit-multi-tenancy"
compatibility_date = "2024-09-03"
# pages_build_output_dir = ".svelte-kit/cloudflare"

# https://kit.svelte.dev/docs/adapter-cloudflare-workers#basic-configuration
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "pnpm run build"
